apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-notes-ingress
spec:
  rules:
  - host: easynotes.lvh.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: easy-notes-service
              port:
                number: 8080